//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adds_images_tbl
    {
        public int id { get; set; }
        public string hiring_period { get; set; }
        public byte[] img_file { get; set; }
        public string img_name { get; set; }
    }
}
