//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adds_images_tbl
    {
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string item_no { get; set; }
        public string img_file_name { get; set; }
        public string file_path { get; set; }
        public string file_url { get; set; }
    }
}
