//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants_rating_tbl
    {
        public string app_ctrl_nbr { get; set; }
        public string psb_ctrl_nbr { get; set; }
        public Nullable<decimal> qs_total_100perc { get; set; }
        public Nullable<decimal> exam_100perc { get; set; }
        public Nullable<decimal> cbi_100rating { get; set; }
        public Nullable<decimal> total_rating { get; set; }
        public Nullable<decimal> score_rendered { get; set; }
        public Nullable<decimal> ipcr_rating { get; set; }
    }
}
