//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants_tbl
    {
        public string info_ctrl_nbr { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string birth_date { get; set; }
        public string gender { get; set; }
        public string civil_status { get; set; }
        public string app_address { get; set; }
        public Nullable<System.DateTime> applied_dttm { get; set; }
        public Nullable<bool> is_employee { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public byte[] empl_photo_img { get; set; }
        public string mobile_number { get; set; }
        public string email_add { get; set; }
    }
}
