//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants_review_tbl_olddata
    {
        public string app_ctrl_nbr { get; set; }
        public string info_ctrl_nbr { get; set; }
        public string item_no { get; set; }
        public string position_code { get; set; }
        public string department_code { get; set; }
        public string employment_type { get; set; }
        public string app_status { get; set; }
        public string budget_code { get; set; }
        public string approval_id { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
    }
}
