//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant_learnanddevt_tbl
    {
        public int seq_no { get; set; }
        public string info_ctrl_nbr { get; set; }
        public string learn_devt_title { get; set; }
        public Nullable<System.DateTime> learn_devt_from { get; set; }
        public Nullable<System.DateTime> learn_devt_to { get; set; }
        public Nullable<double> no_of_hrs { get; set; }
        public string learn_devt_type { get; set; }
        public string conducted_by { get; set; }
        public Nullable<bool> psb_selected { get; set; }
        public string learn_devt_from_2 { get; set; }
        public string learn_devt_to_2 { get; set; }
    }
}
