//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants_review_tbl
    {
        public string app_ctrl_nbr { get; set; }
        public string info_ctrl_nbr { get; set; }
        public string item_no { get; set; }
        public string position_code { get; set; }
        public string department_code { get; set; }
        public string employment_type { get; set; }
        public string app_status { get; set; }
        public string budget_code { get; set; }
        public string approval_id { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public string hiring_period { get; set; }
        public Nullable<System.DateTime> fetch_dttm { get; set; }
        public string fetch_by { get; set; }
        public Nullable<System.DateTime> aknowledge_dttm { get; set; }
        public string aknowledge_by { get; set; }
        public Nullable<System.DateTime> endorse_dttm { get; set; }
        public string endorse_by { get; set; }
        public Nullable<System.DateTime> prescreen_dttm { get; set; }
        public string presreen_by { get; set; }
        public Nullable<System.DateTime> email_aknowldge_regret_dttm { get; set; }
        public string email_aknowldge_regret_by { get; set; }
        public Nullable<System.DateTime> email_regret_dttm { get; set; }
        public string email_regret_by { get; set; }
        public Nullable<System.DateTime> email_noti_exam_dttm { get; set; }
        public string email_noti_exam_by { get; set; }
        public Nullable<System.DateTime> email_notintop5_dttm { get; set; }
        public string email_notintop5_by { get; set; }
        public Nullable<System.DateTime> email_noti_hrmpsb_dttm { get; set; }
        public string email_noti_hrmpsb_by { get; set; }
        public Nullable<System.DateTime> email_congratulatory_dttm { get; set; }
        public string email_congratulatory_by { get; set; }
        public Nullable<System.DateTime> email_aknowldge_dttm { get; set; }
        public string email_aknowldge_by { get; set; }
    }
}
