//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants_email_sent_items
    {
        public string app_ctrl_nbr { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string email_address { get; set; }
        public string hiring_period { get; set; }
        public string email_subject { get; set; }
        public string created_dttm { get; set; }
        public string created_by_user { get; set; }
    }
}
