//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant_attachment_tbl
    {
        public int seq_no { get; set; }
        public string info_ctrl_nbr { get; set; }
        public string doc_type { get; set; }
        public string file_path { get; set; }
        public byte[] filedocs { get; set; }
    }
}
