//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class available_item_hdr_tbl
    {
        public string ctrl_no { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_userby { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_userby { get; set; }
        public System.DateTime active_dttm { get; set; }
        public System.DateTime expiry_dttm { get; set; }
        public Nullable<bool> active_forpsb { get; set; }
    }
}
