//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_criteria3_tbl
    {
        public int criteria3_id { get; set; }
        public Nullable<int> criteria2_id { get; set; }
        public string criteria3_descr { get; set; }
        public string item_order { get; set; }
        public Nullable<int> question_type { get; set; }
    }
}
