//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_rating_questiontype_tbl
    {
        public int question_type { get; set; }
        public string question_type_descr { get; set; }
        public Nullable<int> rscale_group_id { get; set; }
    }
}
