//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_respondent_1_hdr_tbl
    {
        public int respondent_1_id { get; set; }
        public string app_ctrl_nbr { get; set; }
        public string supervisor_name { get; set; }
        public string supervisor_office_address { get; set; }
        public string supervisor_date { get; set; }
        public string interviewed_by { get; set; }
        public string interviewed_date { get; set; }
        public string created_dttm { get; set; }
        public string created_by { get; set; }
        public string updated_dttm { get; set; }
        public string updated_by { get; set; }
    }
}
