//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_rating_scale_tbl
    {
        public int rating_scale_id { get; set; }
        public string rating_scale { get; set; }
        public string rating_scale_descr { get; set; }
        public Nullable<int> group_type_id { get; set; }
    }
}
