//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class change_item_history_tbl
    {
        public string app_ctrl_nbr { get; set; }
        public string item_previous { get; set; }
        public string item_new { get; set; }
        public string hiring_period { get; set; }
        public string created_by { get; set; }
        public string created_dttm { get; set; }
        public string updated_by { get; set; }
        public string updated_dttm { get; set; }
    }
}
