//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_and_approve_dates_tbl
    {
        public string apl_ctrl_nbr { get; set; }
        public Nullable<System.DateTime> email_acknwldg { get; set; }
        public string email_acknwldg_by { get; set; }
        public Nullable<System.DateTime> email_notitop5 { get; set; }
        public string email_notitop5_by { get; set; }
        public Nullable<System.DateTime> email_notiexam { get; set; }
        public string email_notiexam_by { get; set; }
        public Nullable<System.DateTime> email_congratulatory { get; set; }
        public string email_congratulatory_by { get; set; }
        public Nullable<System.DateTime> email_regret { get; set; }
        public string email_regret_by { get; set; }
        public Nullable<System.DateTime> prescreened_on { get; set; }
        public string prescreened_by { get; set; }
        public Nullable<System.DateTime> endorsed_on { get; set; }
        public string endorsed_by { get; set; }
    }
}
