//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class endorsement_print_hdr_tbl
    {
        public int endorse_no { get; set; }
        public string psb_ctrl_nbr { get; set; }
        public System.DateTime endorsement_print_date { get; set; }
        public string endorsement_print_by { get; set; }
    }
}
