//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_PAYEntities : DbContext
    {
        public HRIS_PAYEntities()
            : base("name=HRIS_PAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<personnel_tbl> personnel_tbl { get; set; }
    
        public virtual ObjectResult<sp_budgetyears_tbl_combolist1_Result> sp_budgetyears_tbl_combolist1(string par_employment_type)
        {
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_budgetyears_tbl_combolist1_Result>("sp_budgetyears_tbl_combolist1", par_employment_typeParameter);
        }
    }
}
