//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class onlineAppliedItem_tbl
    {
        public string info_ctrl_nbr { get; set; }
        public string item_no { get; set; }
        public string employment_type { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string budget_code { get; set; }
        public string hiring_period { get; set; }
    }
}
