//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescreen_tbl
    {
        public string empl_id { get; set; }
        public string prescreen_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_by_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_by_dttm { get; set; }
        public string item_no { get; set; }
        public string hiring_period { get; set; }
    }
}
