//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_rating_hdr_tbl
    {
        public string psb_cat_code { get; set; }
        public string cat_descr { get; set; }
        public Nullable<int> max_rate { get; set; }
        public Nullable<bool> rating_status { get; set; }
    }
}
