//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_pnl_rtg_tbl
    {
        public string psb_ctrl_nbr { get; set; }
        public string app_ctrl_nbr { get; set; }
        public string user_id { get; set; }
        public string psb_cat_subcode { get; set; }
        public Nullable<double> psb_pnl_rating { get; set; }
        public Nullable<System.DateTime> rating_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
