//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_hiring_period_tbl
    {
        public string ctrl_nbr { get; set; }
        public string period_from { get; set; }
        public string period_to { get; set; }
        public string budget_code { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string employment_type { get; set; }
        public string period_descr { get; set; }
    }
}
