//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_status_tbl
    {
        public int id { get; set; }
        public int psb_status { get; set; }
        public string psb_status_descr { get; set; }
        public string psb_button_label { get; set; }
    }
}
