//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_rating_dtl_tbl
    {
        public string psb_cat_subcode { get; set; }
        public string psb_cat_code { get; set; }
        public string sub_cat_descr { get; set; }
        public Nullable<int> sub_max_rate { get; set; }
    }
}
