//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_systemsetup_rating_tbl
    {
        public string rtg_ctrl_nbr { get; set; }
        public string rtg_short_descr { get; set; }
        public string rtg_descr { get; set; }
        public int rtg_max_value { get; set; }
        public int rtg_level { get; set; }
        public string rtg_parent_lvl { get; set; }
    }
}
