//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psb_sked_item_nbrs_olddata
    {
        public string item_no { get; set; }
        public string psb_ctrl_nbr { get; set; }
        public Nullable<int> endorse_no { get; set; }
        public Nullable<bool> selected_approved { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
    }
}
