//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selected_applicants_tbl
    {
        public string app_ctrl_nbr { get; set; }
        public string item_no { get; set; }
        public string psb_ctrl_nbr { get; set; }
        public System.DateTime selected_dttm { get; set; }
        public string selected_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
        public string status { get; set; }
    }
}
