//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_applicants_review_tbl
    {
        public string empl_id { get; set; }
        public string app_ctrl_nbr { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string item_no { get; set; }
        public Nullable<System.DateTime> fetch_dttm { get; set; }
        public string fetch_by { get; set; }
        public string app_status { get; set; }
        public string hiring_period { get; set; }
        public Nullable<System.DateTime> prescreen_dttm { get; set; }
        public string presreen_by { get; set; }
        public string email_aknowldge_dttm { get; set; }
        public string email_aknowldge_regret_dttm { get; set; }
        public string email_noti_exam_dttm { get; set; }
        public string email_regret_dttm { get; set; }
        public string email_noti_hrmpsb_dttm { get; set; }
        public string email_notintop5_dttm { get; set; }
        public string email_congratulatory_dttm { get; set; }
    }
}
