//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_available_item_hdr_tbl
    {
        public string ctrl_no { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string descr { get; set; }
        public string active_dttm { get; set; }
        public string expiry_dttm { get; set; }
        public Nullable<bool> active_forpsb { get; set; }
        public int active_status { get; set; }
    }
}
