//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_applicant_for_bi
    {
        public string applicants_name { get; set; }
        public string app_ctrl_nbr { get; set; }
        public string department_name1 { get; set; }
        public string hiring_period { get; set; }
        public string period_descr { get; set; }
        public string period_from { get; set; }
        public string period_to { get; set; }
    }
}
