//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_combined_item_tbl
    {
        public int combined_id { get; set; }
        public string psb_ctrl_nbr { get; set; }
        public string item_no { get; set; }
        public string position_code { get; set; }
        public string employment_type { get; set; }
        public string budget_code { get; set; }
        public string descr { get; set; }
        public string combined_by { get; set; }
        public Nullable<System.DateTime> combined_dttm { get; set; }
    }
}
