//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_educ_type_tbl_sort
    {
        public string educ_type { get; set; }
        public string educ_descr { get; set; }
        public string educ_short_descr { get; set; }
        public string sort_order { get; set; }
    }
}
