//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_exam_schedule_tbl
    {
        public int exam_id { get; set; }
        public string exam_date { get; set; }
        public string exam_time { get; set; }
        public string exam_type { get; set; }
        public string exam_year { get; set; }
        public string exam_location { get; set; }
        public string zoom_link { get; set; }
        public string zoom_meeting_id { get; set; }
        public string zoom_passcode { get; set; }
        public string exam_status { get; set; }
    }
}
