//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_guest_user_info_tbl
    {
        public string g_user_id { get; set; }
        public bool g_status { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string civil_status { get; set; }
        public string civil_status_descr { get; set; }
        public string gender { get; set; }
        public string gender_descr { get; set; }
        public string birth_date { get; set; }
        public string g_address { get; set; }
        public string agency { get; set; }
        public string position { get; set; }
    }
}
