//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_open_vacant_publication_list
    {
        public string ctrl_no { get; set; }
        public string item_no { get; set; }
        public string assignment_code { get; set; }
        public string budget_code { get; set; }
        public string open_dt_fr { get; set; }
        public string open_dt_to { get; set; }
        public string open_status { get; set; }
        public string posted_in { get; set; }
        public string publish_at { get; set; }
        public System.DateTime publish_to { get; set; }
        public string employment_type { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string division_code { get; set; }
        public string empl_id { get; set; }
        public string position_code { get; set; }
        public string section_code { get; set; }
        public string subdepartment_code { get; set; }
        public string position_long_title { get; set; }
        public string position_short_title { get; set; }
        public string position_title1 { get; set; }
        public string position_title2 { get; set; }
    }
}
