//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_psb_sked_app_tbl
    {
        public string psb_ctrl_nbr { get; set; }
        public string app_ctrl_nbr { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string hiring_period { get; set; }
        public Nullable<int> psb_status { get; set; }
        public string item_no { get; set; }
        public Nullable<System.DateTime> psb_date { get; set; }
        public string remarks_details { get; set; }
    }
}
