//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eRSP_Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_return_compentency
    {
        public string item_no { get; set; }
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string position_code { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string competency_required { get; set; }
    }
}
